### ISSUE TITLE
Confusing error message during install when K8s cluster is still initializing

### ISSUE THREAD

**Issue by agemooij** [lightbend/cloudflow#115] opened 2020-01-22 15:15 UTC
**Describe the bug**
After installing the cluster to GKE, it upgrades itself creating the node pools taking the cluster offline for a few minutes. If you try and run install-gke.sh at this time it fails with the misleading error "It looks like you are not logged into a Kubernetes cluster. Please 'gcloud init' before running the installer." The install script assumes any error returned by kubectl get pods command is related to authentication, which isn't always the case.

**Expected behavior**
The script should preferably detect that the cluster is not finished initialization or, if that is not possible, the error message should indicate this might be the case and advise the user to verify this and perhaps wait a little bit for the initialization to finish.

**Comment by skyluc** [comment] 2020-01-29 07:55
It is still a problem with the current master? I add the option to disable the autoupgrade feature in a previous change #83.

**Comment by mrooding** [comment] 2020-02-25 08:32
It still is a problem after your change @skyluc. I verified that both node pools (default-pool & kafka-pool) are set not to auto-update after running the installer. After running the setup script, the Google Cloud UI in the cluster overview states "The cluster is being updated". However, on the cluster page itself, it states "Repairing cluster". Using `gcloud container clusters list` the status is set to "RECONCILING". 

I played around a little bit with adjusting the install script to wait for the repair to be done, but the issue is that just after creating the cluster it is reported as "RUNNING". It actually takes 1-3 minutes before it starts repairing. I haven't been able to figure out why it starts repairing. The operations log (gcloud container operations list) doesn't explain why a certain event happens.

**Comment by mrooding** [comment] 2020-02-27 12:45
I was able to prevent the repairs from happening by explicitly disabling auto-repair after the node pools are created. Unfortunately, there's no way to disable auto-repair during cluster creation.

```
gcloud container node-pools update default-pool --cluster $CLUSTER_NAME --zone $gcloudZone --no-enable-autorepair

gcloud container node-pools update kafka-pool-0 --cluster $CLUSTER_NAME --zone $gcloudZone --no-enable-autorepair
```

It's not pretty but for now, does the job

**Comment by RayRoestenburg** [comment] 2020-06-05 14:10
Closing this since we have deprecated this installer.

**Closed by RayRoestenburg** 2020-06-05 14:10 UTC
Labels: kind/bug, priority/backlog, status:backlog
