### ISSUE TITLE
Allow injecting the SBT version string used for container images and deployment CRs

### ISSUE THREAD

**Issue by thomasschoeftner** [lightbend/cloudflow#618] opened 2020-08-07 11:35 UTC
**Is your feature request related to a problem? Please describe.**
Our CI and build-processes require us to manage the version strings used for container images (and all other published artifacts) outside the build-tool.

**Is your feature request related to a specific runtime of cloudflow or applicable for all runtimes?**
applicable to all Cloudflow runtimes

**Describe the solution you'd like**
It should be possible to override the version string generated by the sbt-cloudflow plugin for the container-images and all other published artifacts.

**Describe alternatives you've considered**
We have considered putting custom code in the `sbt.cloudflow` package and override the usual settings, but this will mean extra maintenance on a continuous basis and may inflict incompatibility with out-of-the-box Cloudflow behavior.

**Additional context**
n/a

**Comment by RayRoestenburg** [comment] 2020-08-19 18:55
It's probably a good idea to surface this same version in the built CR json file?

**Comment by thomasschoeftner** [comment] 2020-08-21 07:44
What do you mean with *surface*?
- add the version string to the CR json file name?
- explicitly add it inside the CR json file?
- reference the container versions/tags using the custom version?

Actually, if a custom version is used, I think it should replace the version string generated from git everywhere.

**Comment by RayRoestenburg** [comment] 2020-09-24 10:53
Sorry, missed this. yes, the version string should replace what is now generated from git.

**Comment by andreaTP** [comment] 2020-10-08 18:28
Since this PR( #768 ) got merged to master you can now achieve the desired behavior:
 - omit `cloudflowDockerRegistry` (or set it to `None`)
 - run `buildApp` and it will generate a CR file using the local versions
 - manually publish the generated docker images

Not straightforward, but feasible :-)

**Comment by thomasschoeftner** [comment] 2020-10-16 19:48
It will be pretty cumbersome to make this work in a CI environment, because publishing would have to be an explicit step after the build. It would have to use the container images managed by the local docker daemon, right?
AFAIK, that would lead to a plethora of workarounds on various levels.

**Comment by andreaTP** [comment] 2020-10-19 11:14
Hey @thomasschoeftner ! Thanks a lot for your feedback, I was testing this "functionality" with the just-released Cloudflow `2.0.11`.
Though the "user API" of the `sbt-plugin` is not set in stone and might change (possibly becoming more friendly and consistent) in the near future, what I ended up with is:
```
val myPublish = taskKey[Unit]("build and publish custom docker image")

cloudflowDockerImageName := Some(cloudflow.sbt.DockerImageName(s"my-registry/${(ThisProject / name).value}", (ThisProject / version).value)),
myPublish := Def.task {
  import sys.process._
  val imageName = (imageNames in docker).value.head

  assert { (s"docker push ${imageName}".!) == 0 }
}.dependsOn(buildApp).value
```

Can I ask you to elaborate on the weaknesses of an approach like this so that we can eventually improve?

We are, currently, already relying on the local docker daemon and guaranteed the sequentially of commands with sbt:
https://github.com/marcuslonnberg/sbt-docker/blob/5cb2f7dfd11cd0d22cee5a94dd668272c6c845fb/src/main/scala/sbtdocker/DockerSettings.scala#L28

**Comment by andreaTP** [comment] 2020-10-19 20:11
Note that I found a bug still preventing from achieving the goal, fortunately, is fixed here: https://github.com/lightbend/cloudflow/pull/806#issue-506244587
I will be happy to publish an RC release to let anyone interested experiment with it.

**Comment by thomasschoeftner** [comment] 2020-10-20 09:59
Thanks for the code snippet, @andreaTP .

I am mainly concerned, because the docker plugin for sbt requires access to the docker daemon (as you point out).
In many CI enviroments (including ours), this boils down to a docker-in-docker approach.
So I am worried about conflicting parallel builds using the docker daemon on the same build server...

On the bright side, what you point out, could actually be a means how to get more grip on builds.
In fact, I'd like the be able to build-and-publish (`buildApp`) only a specific  sub-project, as our SBT project contains a couple of Cloudflow applications.
Your code snipped only contains the actual publishing step, but what's missing to emulate `buildApp` for a single SBT sub-project?

Thx for any pointers!

**Comment by andreaTP** [comment] 2020-10-21 09:37
Hey @thomasschoeftner !

> I am mainly concerned, because the docker plugin for sbt requires access to the docker daemon (as you point out).
In many CI enviroments (including ours), this boils down to a docker-in-docker approach.
So I am worried about conflicting parallel builds using the docker daemon on the same build server...

This is correct, but it's not any different/worst than what is already happening under the curtain. To stay on the safe side I would use a consistent versioning system that avoids concurrent image builds to end up with the same tag; in cloudflow we use for example [dynver](https://github.com/lightbend/cloudflow/blob/master/core/project/plugins.sbt#L4)

> In fact, I'd like the be able to build-and-publish (buildApp) only a specific sub-project, as our SBT project contains a couple of Cloudflow applications.

This is already, "by-design":
```scala
sbt <sub-project>/buildApp
```

> Your code snipped only contains the actual publishing step, but what's missing to emulate buildApp for a single SBT sub-project?

Correct, this is because, right now, if you **don't set** `cloudflowDockerRegistry` the behavior is that it will generate docker image + CR file based on the project version and not using the complete `sha` without publishing the generated image. So, you do need to publish the image by yourself, and in the snippet you have a possible approach.

I encourage you to experiment the new workflow by setting:
```
cloudflowDockerRegistry := None
```
or by completely omitting it!

Please note that in version 2.0.11 the CR file is probably going to be incorrect, but this is fixed in master and is going to be available very shortly (alternatively, you can test by using a locally published version of the sbt-plugin and specifying `cloudflowVersion := "2.0.11" in the target build.sbt`), feel free to reach me out for additional guidance if needed!

**Comment by thomasschoeftner** [comment] 2020-10-21 11:46
Hi @andreaTP ,

AFAIK, `buildApp` will try and build / publish all Cloudflow applications in the project - even in other sub-projects without dependency. At least that's how it appears if I watch the `sbt "project <sub-project>" buildApp` logs.

Yeah, I know about the invalid CR in 2.0.11... ;)

**Comment by RayRoestenburg** [comment] 2020-10-21 12:16
`buildApp` from a project that uses CloudflowApplication will only build that app. It will consider all streamlets in all other sub projects, since it can use any of them. eventually you only get the output for one application, for instance here I modified taxi-ride example to have two pipelines, and built the app for pipeline 2:
```
> project taxi-ride-pipeline2
[info] Set current project to taxi-ride-fare2 (in build file:/redacted/src/cloudflow/examples/taxi-ride/)
> buildApp
[info] Streamlet 'taxiride.logger.FarePerRideLogger' found
[info] Streamlet 'taxiride.processor.TaxiRideProcessor' found
[info] Streamlet 'taxiride.ingestor.Generator' found
[info] Streamlet 'taxiride.ingestor.TaxiFareIngress' found
[info] Streamlet 'taxiride.ingestor.TaxiRideIngress' found
[success] /redacted/taxi-ride/taxi-ride-pipeline2/src/main/blueprint/blueprint.conf verified.
[info] Wrote /redacted/taxi-ride/ingestor/target/scala-2.12/ingestor_2.12-2.0.11-22-3896c984-20201021-1409.pom
[info] Wrote /redacted/examples/taxi-ride/processor/target/scala-2.12/processor_2.12-2.0.11-22-3896c984-20201021-1409.pom
[info] Wrote /<redacted>/cloudflow/examples/taxi-ride/logger/target/scala-2.12/logger_2.12-2.0.11-22-3896c984-20201021-1409.pom
[info] Streamlet 'taxiride.logger.FarePerRideLogger' found
[info] Streamlet 'taxiride.ingestor.Generator' found
[info] Streamlet 'taxiride.ingestor.TaxiFareIngress' found
[info] Streamlet 'taxiride.ingestor.TaxiRideIngress' found
[info] Wrote /<redacted>/taxi-ride/datamodel/target/scala-2.12/datamodel_2.12-2.0.11-22-3896c984-20201021-1409.pom
[warn] You have no main class in your project. No start script will be generated.
[warn] You have no main class in your project. No start script will be generated.
[warn] You have no main class in your project. No start script will be generated.
[warn] You have no main class in your project. No start script will be generated.
[info] Streamlet 'taxiride.processor.TaxiRideProcessor' found
[warn] You have no main class in your project. No start script will be generated.
[warn] You have no main class in your project. No start script will be generated.
[info] Sending build context to Docker daemon  74.67MB
... docker build and push omitted
[success] Cloudflow application CR generated in /<redacted>/target/taxi-ride-fare2.json
[success] Use the following command to deploy the Cloudflow application:
[success] kubectl cloudflow deploy /<redacted>/target/taxi-ride-fare2.json
[success] Total time: 36 s, completed Oct 21, 2020 2:12:18 PM
 root/taxi-ride-pipeline2>
```

**Comment by andreaTP** [comment] 2020-10-21 12:58
I can confirm what @RayRoestenburg wrote, and I have tracked the request of building only the specific docker images in #814 ( @thomasschoeftner please go ahead and elaborate on the subject! ).

Getting back at the subject of this issue, I think we are covered with all the elements to say that:

> Allow injecting the SBT version string used for container images and deployment CRs

is now supported, starting from, well 😄 , the next version (coming shortly BTW).

I wait for you @thomasschoeftner to confirm and for the next release.

**Comment by thomasschoeftner** [comment] 2020-10-22 14:30
Ok, seems to do the trick!

Let me wrap it up:
Setting `cloudflowDockerRegistry := None`, makes `sbt buildApp` ise the common `version` property for deployment descriptors (CRs) and container image tags.
We can push the container image cached by the local docker daemon to GCR (or wherever) with a custom SBT task (or another build step in the CI).

cool!

**Comment by andreaTP** [comment] 2020-10-22 14:45
@thomasschoeftner yup, that's it! Great summary!

You can already test using the nightly sbt plugin version: `2.0.11-10222020`
and specify in the `build.sbt` `cloudflowVersion := "2.0.11"`

**Comment by RayRoestenburg** [comment] 2020-10-29 09:23
Can this be closed?

**Comment by thomasschoeftner** [comment] 2020-10-31 06:41
Yes, I think so.

**Closed** 2020-11-06 17:31 UTC
Labels: productboard
